In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [62]:
df = pd.read_csv("Excels\\fake_news.csv")
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [63]:
df.shape

(20800, 5)

In [64]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [65]:
df = df.fillna('')

In [66]:
df.isna().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [67]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [70]:
from sklearn.model_selection import train_test_split
X = df.drop(['label','id'],axis='columns')
y = df['label']

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.25)

In [75]:
X_train.values

array([['', 'uncommon sense', 'That would be unconstitutional.'],
       ['EXCLUSIVE: Trump Has ’Less Kinetic’ Option in Afghanistan',
        'Kristina Wong',
        'President Donald Trump is deciding between two rival ideas  —   one more “kinetic” and the other “less kinetic”  —   for U. S. strategy in Afghanistan, according to a senior White House official. [On one side are the military strategists, who favor a robust U. S. military approach to resolving the    Afghanistan war  —   hitting the Taliban harder and pressuring them back to the negotiating table. It would also include more spending on building the Afghan government’s capacity, and entail more overall funding, troops, and resources.  On the other side are those who want to maintain the current level of troops but limit U. S. involvement in the war. That option would leave it up to the Afghan government and the Taliban to resolve the conflict, but assist the Afghan government with a minimal    mission, also known as “for

In [80]:
# Very good for Message Features or Text Features ( email spam )
from sklearn.feature_extraction.text import CountVectorizer
# Join the lists of strings into single strings
X_train_str = [' '.join(text) for text in X_train.values]

# Instantiate CountVectorizer with lowercase=False
vc = CountVectorizer(lowercase=False)

# Fit and transform the training data
X_train_count = vc.fit_transform(X_train_str)

# Print the token counts of the first three samples
print(X_train_count.toarray()[:3])

[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [87]:
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [88]:
X_test_str = [' '.join(text) for text in X_test.values]

# Transform X_test
X_test_count = vc.transform(X_test_str)

# Score the model
score = model.score(X_test_count, y_test)
print("Model accuracy on test data:", score)

Model accuracy on test data: 0.9303846153846154


# Another Way

In [90]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [91]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\musta\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [92]:
# printing the stopwords in English
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [93]:
df = pd.read_csv("Excels\\fake_news.csv")
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [94]:
df.shape

(20800, 5)

In [95]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [96]:
df = df.fillna('')

In [97]:
df['content'] = df['author'] + ' ' + df['title']

In [98]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  \
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1  Ever get the feeling your life circles the rou...      0   
2  Why the Truth Might Get You Fired October 29, ...      1   
3  Videos 15 Civilians Killed In Single US Airstr...      1   
4  Print \nAn Iranian woman has been sentenced to...      1   

                                             content  
0  Darrell Lucus House Dem Aide: We Didn’t Even S...  
1  Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...  
2  Consortiumnews.com Why the Truth Might Get You...  
3  Jessica Purkiss 15 Civilians Killed In Single ...  
4  Howard Portnoy Iranian woman jailed for fictio...

In [100]:
X = df.drop(['label','id'], axis='columns')
Y = df['label']

Stemming:

Stemming is the process of reducing a word to its Root word

example: actor, actress, acting --> act

In [101]:
port_stem = PorterStemmer()

In [102]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [103]:
df['content'] = df['content'].apply(stemming)

In [104]:
df['content']

0        darrel lucu hous dem aid even see comey letter...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...                        
20795    jerom hudson rapper trump poster child white s...
20796    benjamin hoffman n f l playoff schedul matchup...
20797    michael j de la merc rachel abram maci said re...
20798    alex ansari nato russia hold parallel exercis ...
20799                            david swanson keep f aliv
Name: content, Length: 20800, dtype: object

In [106]:
X = df['content'].values
Y = df['label'].values

In [107]:
X

array(['darrel lucu hous dem aid even see comey letter jason chaffetz tweet',
       'daniel j flynn flynn hillari clinton big woman campu breitbart',
       'consortiumnew com truth might get fire', ...,
       'michael j de la merc rachel abram maci said receiv takeov approach hudson bay new york time',
       'alex ansari nato russia hold parallel exercis balkan',
       'david swanson keep f aliv'], dtype=object)

In [108]:
Y

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [109]:
# converting the textual data to numerical data
vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

In [111]:
print(X)

  (0, 15686)	0.28485063562728646
  (0, 13473)	0.2565896679337957
  (0, 8909)	0.3635963806326075
  (0, 8630)	0.29212514087043684
  (0, 7692)	0.24785219520671603
  (0, 7005)	0.21874169089359144
  (0, 4973)	0.233316966909351
  (0, 3792)	0.2705332480845492
  (0, 3600)	0.3598939188262559
  (0, 2959)	0.2468450128533713
  (0, 2483)	0.3676519686797209
  (0, 267)	0.27010124977708766
  (1, 16799)	0.30071745655510157
  (1, 6816)	0.1904660198296849
  (1, 5503)	0.7143299355715573
  (1, 3568)	0.26373768806048464
  (1, 2813)	0.19094574062359204
  (1, 2223)	0.3827320386859759
  (1, 1894)	0.15521974226349364
  (1, 1497)	0.2939891562094648
  (2, 15611)	0.41544962664721613
  (2, 9620)	0.49351492943649944
  (2, 5968)	0.3474613386728292
  (2, 5389)	0.3866530551182615
  (2, 3103)	0.46097489583229645
  :	:
  (20797, 13122)	0.2482526352197606
  (20797, 12344)	0.27263457663336677
  (20797, 12138)	0.24778257724396507
  (20797, 10306)	0.08038079000566466
  (20797, 9588)	0.174553480255222
  (20797, 9518)	0.295420

In [112]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=2)

In [113]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

In [117]:
scores = cross_val_score(LogisticRegression(),X_train,Y_train,cv=5)
scores.mean()

0.973497596153846

In [118]:
scores = cross_val_score(MultinomialNB(),X_train,Y_train,cv=5)
scores.mean()

0.9499399038461538

In [120]:
model = LogisticRegression().fit(X_train,Y_train)
model.score(X_test,Y_test)

0.9790865384615385

In [123]:
X_new = X_test[3]

y_pred = model.predict(X_new)
print(y_pred)

if (y_pred[0]==0):
  print('The news is Real')
else:
  print('The news is Fake')

[0]
The news is Real


In [127]:
prediction = model.predict(X_test)
prediction

for i in range(len(prediction)):
    if prediction[i] == 1:  # Assuming 1 represents 'Fake News' class
        print('Fake News')
    else:
        print('Real News')


Fake News
Real News
Fake News
Real News
Real News
Fake News
Real News
Fake News
Fake News
Fake News
Real News
Fake News
Fake News
Real News
Fake News
Real News
Fake News
Fake News
Real News
Real News
Real News
Fake News
Real News
Real News
Real News
Real News
Fake News
Real News
Fake News
Real News
Fake News
Real News
Fake News
Fake News
Fake News
Real News
Real News
Fake News
Real News
Real News
Fake News
Real News
Real News
Fake News
Real News
Real News
Fake News
Fake News
Fake News
Fake News
Fake News
Fake News
Fake News
Fake News
Fake News
Fake News
Real News
Fake News
Real News
Fake News
Fake News
Fake News
Fake News
Real News
Real News
Fake News
Fake News
Fake News
Real News
Real News
Fake News
Fake News
Real News
Real News
Real News
Real News
Fake News
Fake News
Real News
Fake News
Fake News
Fake News
Fake News
Real News
Fake News
Real News
Fake News
Real News
Fake News
Fake News
Fake News
Real News
Fake News
Fake News
Real News
Real News
Fake News
Fake News
Fake News
Fake News
