In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[9, 5]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[29, 4], [9, 5], [18, 3], [4, 22, 8], [18, 19, 17], [1, 4], [2, 19, 3], [9, 12], [9, 15], [20, 11]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[29  4  0  0]
 [ 9  5  0  0]
 [18  3  0  0]
 [ 4 22  8  0]
 [18 19 17  0]
 [ 1  4  0  0]
 [ 2 19  3  0]
 [ 9 12  0  0]
 [ 9 15  0  0]
 [20 11  0  0]]


In [5]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))  # Corrected variable name
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

C:\Users\mustafa\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [6]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary() # idk why

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 4, 4)                │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 137 (548.00 B)

 Trainable params: 137 (548.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.fit(X,y,epochs=50,verbose=0)

In [9]:
loss , accuracy = model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - accuracy: 0.9000 - loss: 0.6425


0.8999999761581421

In [10]:
weights = model.get_layer('embedding').get_weights()[0] # weights for the embedding vector
weights

array([[ 4.3692052e-02,  1.8598055e-02,  3.5458878e-03,  3.8564898e-02],
       [-8.9228995e-02, -2.2584271e-02,  9.5652059e-02, -2.9573822e-02],
       [-2.7379258e-02, -4.5755468e-03,  3.3136446e-02, -6.5215208e-02],
       [-4.2368788e-02, -5.0922461e-02, -2.1805242e-03,  7.9636328e-02],
       [-4.9778121e-03,  1.5358953e-04, -4.7147166e-02,  6.6643745e-02],
       [-4.5809932e-02, -9.5995829e-02, -6.6833701e-03,  4.1413028e-02],
       [ 2.9343758e-02,  4.6882931e-02,  4.7375742e-02, -9.4986074e-03],
       [ 3.0336585e-02,  2.7132560e-02, -3.6647342e-02,  3.5395052e-02],
       [-8.3165385e-02,  6.4075582e-02, -6.1827473e-02, -3.1672127e-03],
       [-5.7278078e-02, -7.0244655e-02,  6.3621953e-02, -6.5926269e-02],
       [-3.0012786e-02, -2.1976292e-02, -5.0758831e-03, -2.3116088e-02],
       [ 9.5149964e-02,  3.2745931e-02,  9.1446951e-02, -2.4176307e-02],
       [ 7.1641937e-02,  6.1395451e-02,  9.5612578e-02, -8.2354378e-03],
       [ 2.8358214e-03, -4.9747791e-02, -3.0806160e

In [11]:
len(weights) # because vocab size = 30

30